# file: defaults/main.yml -- main variables
#
#

# Basic settings
postgresql_package_state: installed
postgresql_service_name: postgresql
postgresql_data_dir: /var/lib/pgsql/data 
postgresql_conf_dir: "{{ postgresql_data_dir }}"
postgresql_exec_dir: /usr/bin
postgresql_encoding: utf8
postgresql_locale: en_US.utf8


# Stop postgresql service if started and drop cluster if existing.
postgresql_drop_old_cluster: false

# PostgreSQL parameters which will appears in the postgresql.conf
postgresql_conf_default_guc:
  - { regexp: "^#?listen_addresses = .*$", guc: "listen_addresses = '*'" }
  - { regexp: "^#?wal_level = .*$", guc: "wal_level = {{'hot_standby'}}" }
  - { regexp: "^#?max_wal_senders = .*$", guc: "max_wal_senders = {{ groups['postgresql-slaves']|length + 1 }}" }
  - { regexp: "^#?wal_keep_segments = .*$", guc: "wal_keep_segments = {{ 256 }}" }
  - { regexp: "^#?hot_standby = .*$", guc: "hot_standby = {{ 'on' }}" }
  - { regexp: "^#?synchronous_standby_names = .*$", guc: "synchronous_standby_names = '*'" }

# Postgres users to be created (optional)
postgresql_users:
- { name: "web-educaton", pass: "We1234", flags: "LOGIN,SUPERUSER" }


# Specify database cluster location in case when /var/lib/pgsql/x.y/data directory should be replaced with symlink.
postgresql_cluster_symlink_src: ""

#postgresql_replication_user:
#  name: rep
#  pass: changeme

# PostgreSQL service users
postgresql_admin_user: "postgres"

# PostgreSQL databases and settings. Do not remove template, encoding, collate, ctype options from postgresql_database because it most certainly lead to Ansible role inoperability.
#postgresql_databases:
# - { name: "db1", owner: "postgres", template: "template0", encoding: "{{ postgresql_encoding }}", collate: "{{ postgresql_locale }}", ctype: "{{ postgresql_locale }}" }

# Extensions which will be installed into databases. This list of extensions will be installed to all databases within postgresql_databases.
postgresql_extensions:
 - hstore
 - pg_stat_statements

# Settings related to the pg_hba rules
postgresql_default_unix_auth_method: "trust"
postgresql_default_ipv4_auth_method: "md5"
postgresql_default_ipv6_auth_method: "md5"

# Specify default rules for pg_hba.conf. Change them only if it is really necessary.
postgresql_pg_hba_default:
 - { type: local, database: all, role: "{{ postgresql_admin_user }}", address: "", method: "{{ postgresql_default_unix_auth_method }}", comment: '"local" is for Unix domain socket connections only' }
 - { type: host, database: all, role: all, address: "127.0.0.1/32", method: "{{ postgresql_default_ipv4_auth_method }}", comment: 'IPv4 local connections:' }
 - { type: host, database: all, role: all, address: "::1/128", method: "{{ postgresql_default_ipv6_auth_method }}", comment: 'IPv6 local connections:' }

# Specify custom rules for pg_hba.conf. Specify here all necessary pg_hba rules.
#postgresql_pg_hba_custom:
# - { type: host, database: replication, role: "{{ postgresql_admin_user }}", address: "127.0.0.1/32", method: "{{ postgresql_default_ipv4_auth_method }}", comment: '' }
