---
# Install and setup PostgreSQL with Streaming Replication
- hosts: all
  become: yes
  become_user: root
  vars_files:
    - 'defaults/main.yml'
  tasks:
  - include: 'tasks/install.yml'

#- hosts: streaming-master
#  sudo: yes
#  sudo_user: root
#  vars_files:
#    - 'defaults/main.yml'
#  tasks:
#  - group_by: key=os_{{ ansible_os_family }}
#  - include: 'tasks/configure-master.yml'
#  - include: 'tasks/users.yml'
#  - include: 'tasks/databases.yml'
