# handlers/main.yml 

- name: restart postgresql
  service: 
    name: "{{ postgresql_service_name }}"
    state: restarted
    enabled: yes

- name: reload postgresql
  service: 
    name: "{{ postgresql_service_name }}"
    state: reloaded
    enabled: yes
