# file: tasks/configure-master.yml -- postgresql pre-start configuration of master server and startup

- name: "Check cluster directory exists"
  stat:
    path: "{{ postgresql_data_dir }}"
  register: postgresql_data_stat

- name: "Check cluster directory is empty"
  find:
    paths: "{{ postgresql_data_dir }}"
  register: postgresql_data_find 

- name: "Initialize new postgresql cluster"
  become: true
  become_user: "{{ postgresql_admin_user }}"
  command: "{{ postgresql_exec_dir }}/initdb --encoding '{{ postgresql_encoding }}' --pgdata {{ postgresql_data_dir }} --locale '{{ postgresql_locale }}'"
  when: postgresql_data_stat.stat.exists == False or postgresql_data_find.matched|int == 0
  notify:
    - restart postgresql

- name: "Configure pg_hba.conf"
  template:
    src: pg_hba.conf.j2
    dest: "{{ postgresql_conf_dir }}/pg_hba.conf"
    owner: "{{ postgresql_admin_user }}"
    group: "{{ postgresql_admin_user }}"
    mode: 0600
  register: result

- name: reload postgresql
  service:
    name: "{{ postgresql_service_name }}"
    state: reloaded
    enabled: yes
  when: result|changed

- name: "Configure postgresql.conf"
  lineinfile:
    dest: "{{ postgresql_conf_dir }}/postgresql.conf"
    state: present
    regexp: "{{ item.regexp }}"
    line: "{{ item.guc }}"
  with_items: "{{ postgresql_conf_default_guc }}"
  notify:
    - restart postgresql

- name: "Start postgresql service"
  service: 
    name: "{{ postgresql_service_name }}"
    state: started
    enabled: yes
