---
- name: Installing postgresql
  include: 'install.yml'
  tags:
    - install

- name: Configuring postgresql
  include: 'general-configure.yml'

- name: Configuring the postgresql master
  include: 'configure-master.yml'
  when: postgresql_master|default(false)|bool == true
  tags:
    - configure

#- include: 'users.yml'
#  when: postgresql_master == 'true'
#- include: 'databases.yml'
#  when: postgresql_master == 'true'
#
#- name: Configuring slaves
#  include: 'configure-slaves.yml'
#  when: postgresql_master == 'false'
