---
- name: Installing postgresql
  include: 'install.yml'
  tags:
    - install

#- name: Configuring postgresql
#  include: 'general-configure.yml'
#  tags:
#    - configure

- name: Configuring the postgresql master
  include: 'configure-master.yml'
  when: '"postgresql-master" in group_names'
  tags:
    - configure

#- include: 'users.yml'
#  when: postgresql_master == 'true'
#- include: 'databases.yml'
#  when: postgresql_master == 'true'
#
#- name: Configuring slaves
#  hosts: 
#    - "{{ postgresql_slaves_group }}"
#  include: 'configure-slaves.yml'
#  when: postgresql_master == 'false'
