---
- name: Installing postgresql
  include: 'install.yml'

- name: Configuring the postgresql master
  include: 'configure-master.yml'
  when: '"postgresql-master" in group_names'
- include: 'users.yml'
  when: '"postgresql-master" in group_names'
#- include: 'databases.yml'
#  when: '"postgresql-master" in group_names'

- name: Configuring the postgresql slaves
  include: 'configure-slaves.yml'
  when: '"postgresql-slaves" in group_names'
